

SELECT * FROM customer limit 20

--What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
group by gender;

--Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Compare the average purchase amounts between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard', 'Express')
group by shipping_type;

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Which 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
FROM customer
group by item_purchased
order by discount_rate desc
limit 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases , and show the count of each segment?
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
FROM customer
)

SELECT customer_segment, count(*) as "Number of customers"
FROM customer_type
group by customer_segment;

--What are the Top 3 most purchased products within each category?
WITH item_counts as(
SELECT category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
FROM customer
group by category,item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
group by subscription_status;

--What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
group by age_group
order by total_revenue desc;









